	<?php $this->load->view('emb_header', array('page_title'=>$page_title))?>


	<div id="container">
	
	
		<h1><?=$page_title?></h1>

		<div id="nav">
			<ul>
				<li><a href="<?=site_url()?>/main/today">Today &rArr;</a></li>
				<li><a href="<?=site_url()?>/main/yesterday">Yesterday &rArr;</a></li>
				<li><a href="<?=site_url()?>/main/lastsevendays">Last seven days &rArr;</a></li>
				<li><a href="<?=site_url()?>/main/lastmonth">Last month &rArr;</a></li>
				<li><a href="<?=site_url()?>/main/index">All time &rArr;</a></li>
			</ul>
		</div>

		
		<?php if ($period_start && $period_duration): ?>
			<h2><?=date('l, F j, Y', strtotime($period_start));?> – <?=date('l, F j, Y T', strtotime("$period_start +$period_duration days"));?></h2>
		<?php endif ?>
		
	
		<div id="chart"><img src="<?php echo $chart_url?>" /></div>

		<div id="note">
		This data is derived from 20-message slices taken every minute from the Twitter public timeline. It currently reports the overall usage since the data collection began (2008-07-31), as well as a few common time periods.<p />

		If you're looking for a desktop Twitter client, you might consider <a href="http://funkatron.com/spaz">Spaz</a>, an open-source Twitter client written in JavaScript for the AIR platform.<p />
		
		These stats are collected by a <a href="http://php.net/" title="PHP: Hypertext Preprocessor">PHP</a> script and stored in a <a href="http://incubator.apache.org/couchdb/" title="Apache CouchDB: The CouchDB Project">CouchDB</a> server. <a href="http://codeigniter.com">CodeIgniter</a>, a PHP framework, was used to create this web app. The chart is generated by the <a href="http://code.google.com/apis/chart/" title="Developer&#39;s Guide - Google Chart API - Google Code">Google Chart API</a>, and the sortable table is courtesy of <a href="http://jquery.com/" title="jQuery: The Write Less, Do More, JavaScript Library">jQuery</a> + <a href="http://tablesorter.com/" title="jQuery plugin: Tablesorter 2.0">tablesorter</a>.  Source code is available <a href="http://github.com/funkatron/twitter-stats-tracker/tree/master">on Github</a>.<p />
		
		Contact me on Twitter: <a href="http://twitter.com/funkatron">@funkatron</a><p />
		
		<?php if (isset($last_updated)): ?>
		<em><strong>Last updated:</strong> <?=date('l, F j, Y \a\t g:i:s a T', $last_updated)?></em><p />	
		<?php endif ?>
		
		
		</div>
		
		<div id="ad">
			Funkatron.com is hosted at <a href="http://vpslink.com/vps-hosting/?ref=F48BHZ" target="_blank">VPSLink.com</a>, and I like it a lot. They're pretty cheap, and quite reliable in my experience. If you sign up with them, I get a little money to help out with my own hosting costs. Thanks! 
		</div>


		<table id="full-list" class="tablesorter">
			<thead>
			<tr>
				<th>App</th>
				<th>%</th>
			</tr>
			</thead>
			<tbody>
			<?foreach($source_counts as $key=>$val):?>
			<tr>
				<td><?=$key?></td>
				<td><?=number_format(($val/$sources_total)*100, 3)?>%</td>
			</tr>
			<?endforeach;?>
			</tbody>
		</table>

	</div>

	<?$this->load->view('emb_footer')?>
