	<?php $this->load->view('emb_header', array('page_title'=>$page_title))?>


	<div id="container">

		<div id="main">
			<h1><?=$page_title?></h1>

			<div id="nav">
				<ul>
					<li><a href="<?=site_url()?>lasthour">Last Hour &raquo;</a></li>
					<li><a href="<?=site_url()?>lastday">Last Day &raquo;</a></li>
					<li><a href="<?=site_url()?>lastweek">Last Week &raquo;</a></li>
					<li><a href="<?=site_url()?>last30days">Last 30 days &raquo;</a></li>
					<li><a href="<?=site_url()?>last90days">Last 90 days &raquo;</a></li>
					<li><a href="<?=site_url()?>last180days">Last 180 days &raquo;</a></li>
					<li><a href="<?=site_url()?>all">All time &raquo;</a></li>
				</ul>
			</div>

		
			<?php if ($period_start && $period_duration): ?>
				<h2><?=date('l, F j, Y', strtotime($period_start));?> – <?=date('l, F j, Y T', strtotime("$period_start +$period_duration days"));?></h2>
			<?php endif ?>
		
	
			<div id="chart"><a href="<?php echo $gchart_url?>" target="_blank"><img src="<?php echo $gchart_url?>" border="0" /></a></div>

			<form onsubmit="return false;" id="searchform">
				<label for="search_app_name">Search app name</label>
				<input type="text" name="search_app_name" value="" id="search_app_name">
			</form>

			<div id="myGrid"></div>
		</div>

		<div id="sidebar">
			
			<div id="ad">
				Funkatron.com is hosted at <a href="http://vpslink.com/vps-hosting/?ref=F48BHZ" target="_blank">VPSLink.com</a>, and I like it a lot. They're pretty cheap, and quite reliable in my experience. If you sign up with them, I get a little money to help out with my own hosting costs. Thanks! 
			</div>
			
			<div id="note">
			<strong>You can get this data as JSON</strong>. Just add <code>.json</code> to the url:
			<ul style="margin-top:0px">
				<li><code>/lasthour.json</code></li>
				<li><code>/lastday.json</code></li>
				<li><code>/lastweek.json</code></li>
				<li><code>/last30days.json</code></li>
				<li><code>/last90days.json</code></li>
				<li><code>/last180days.json</code></li>
			</ul>
				
			If you like this, check out <a href="http://getspaz.com">Spaz</a>, an open-source microblogging client written in JavaScript.<p></p>

			These stats are collected by a PHP script and stored in a MySQL database. Static JSON files are dumped from the collected data on a regular basis. <a href="http://codeigniter.com">CodeIgniter</a>, a PHP framework, was used to create this web app. The chart is generated by the <a href="http://code.google.com/apis/chart/" title="Developer&#39;s Guide - Google Chart API - Google Code">Google Chart API</a>, and the sortable table is courtesy of <a href="http://jquery.com/" title="jQuery: The Write Less, Do More, JavaScript Library">jQuery</a> + <a href="http://github.com/mleibman/SlickGrid/" title="ClickGrid">SlickGrid</a>.  Source code is available <a href="http://github.com/funkatron/twitter-stats-tracker/tree/master">on Github</a>.<p></p>

			Contact me on Twitter: <a href="http://twitter.com/funkatron">@funkatron</a><p></p>

			</div>


			
		</div>

	</div>

	<?$this->load->view('emb_footer')?>
